#!/bin/sh
# We need to back-export WAYLAND_DISPLAY -- how about
#	swaymsg exec 'echo $WAYLAND_DISPLAY'
# to where? A file like a pidfile? To be sourced from ../conf.sh ig. But where
# will swaymsg get the SWAYSOCK?

exec 2>&1
sv start dbus-session # Get dbus-session if we can, like dinit(8) <waits-for>
# TODO: some equivalent of dinit(8) <after: ssh-agent>
set -efu
. "$SVDIR"/../conf.sh

cd
exec sway
