#!/bin/sh
# We need to back-export WAYLAND_DISPLAY -- how about
#	SWAYSOCK=$XDG_RUNTIME_DIR/sway-ipc.`id -u`.$$.sock swaymsg 'exec echo $WAYLAND_DISPLAY > where'
# to where? A file like a pidfile? To be sourced from ../conf.sh ig
# Could put it in `check', where it becomes
#	SWAYSOCK=$XDG_RUNTIME_DIR/sway-ipc.`id -u`.`cat supervise/pid`.sock swaymsg 'exec echo $WAYLAND_DISPLAY > where'

exec 2>&1
sv start dbus-session # Get dbus-session if we can, like dinit(8) <waits-for>
# TODO: some equivalent of dinit(8) <after: ssh-agent>
set -efu
. "$SVDIR"/../conf.sh

cd
exec sway
